begin;

create table public.ingredient_categories (
  id bigint generated by default as identity primary key,
  name text not null
    check (btrim(name) <> ''),
  display_order integer not null default 0
    check (display_order >= 0),
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

create unique index ingredient_categories_normalized_name_unique
on public.ingredient_categories (lower(btrim(name)));

insert into public.ingredient_categories (
  name,
  display_order,
  is_active
)
values
  ('เนื้อสัตว์', 10, true),
  ('ผัก', 20, true),
  ('ข้าวและเส้น', 30, true),
  ('ไข่และผลิตภัณฑ์นม', 40, true),
  ('เครื่องปรุง', 50, true),
  ('ของแห้ง', 60, true),
  ('เครื่องดื่ม', 70, true),
  ('บรรจุภัณฑ์', 80, true),
  ('อื่น ๆ', 90, true);

alter table public.ingredients
add column category_id bigint null;

alter table public.ingredients
add constraint ingredients_category_id_fkey
foreign key (category_id)
references public.ingredient_categories (id)
on update cascade
on delete set null;

create index ingredients_category_id_idx
on public.ingredients (category_id);

update public.ingredients
set category_id = (
  select id
  from public.ingredient_categories
  where lower(btrim(name)) = lower(btrim('อื่น ๆ'))
  limit 1
)
where category_id is null;

create or replace function public.protect_other_ingredient_category()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  if pg_catalog.btrim(old.name) = 'อื่น ๆ' then
    if tg_op = 'DELETE' then
      raise exception 'หมวดวัตถุดิบ "อื่น ๆ" ไม่สามารถลบได้'
        using errcode = '23514';
    end if;

    if new.name is distinct from old.name then
      raise exception 'หมวดวัตถุดิบ "อื่น ๆ" ไม่สามารถเปลี่ยนชื่อได้'
        using errcode = '23514';
    end if;

    if new.is_active is false
      and new.is_active is distinct from old.is_active then
      raise exception 'หมวดวัตถุดิบ "อื่น ๆ" ไม่สามารถปิดใช้งานได้'
        using errcode = '23514';
    end if;
  end if;

  if tg_op = 'DELETE' then
    return old;
  end if;

  return new;
end;
$$;

create trigger protect_other_ingredient_category
before update or delete on public.ingredient_categories
for each row
execute function public.protect_other_ingredient_category();

revoke all
on function public.protect_other_ingredient_category()
from public, anon, authenticated;

alter table public.ingredient_categories enable row level security;

revoke all privileges
on table public.ingredient_categories
from anon, authenticated;

grant select, insert, update
on table public.ingredient_categories
to authenticated;

revoke all privileges
on sequence public.ingredient_categories_id_seq
from anon, authenticated;

grant usage, select
on sequence public.ingredient_categories_id_seq
to authenticated;

create policy "authenticated_can_read_ingredient_categories"
on public.ingredient_categories
for select
to authenticated
using (auth.uid() is not null);

create policy "authenticated_can_insert_ingredient_categories"
on public.ingredient_categories
for insert
to authenticated
with check (auth.uid() is not null);

create policy "authenticated_can_update_ingredient_categories"
on public.ingredient_categories
for update
to authenticated
using (auth.uid() is not null)
with check (auth.uid() is not null);

commit;
