begin;

create table public.menu_option_groups (
  id bigint generated by default as identity primary key,
  menu_id bigint not null,
  name text not null,
  selection_type text not null,
  is_required boolean not null default false,
  min_select integer not null default 0,
  max_select integer not null,
  max_total_quantity integer not null,
  display_order integer not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),

  constraint menu_option_groups_name_not_blank_check
    check (btrim(name) <> ''),

  constraint menu_option_groups_selection_type_check
    check (selection_type in ('single', 'multiple')),

  constraint menu_option_groups_display_order_check
    check (display_order >= 0),

  constraint menu_option_groups_min_select_check
    check (min_select >= 0),

  constraint menu_option_groups_max_select_check
    check (max_select >= 1),

  constraint menu_option_groups_select_range_check
    check (min_select <= max_select),

  constraint menu_option_groups_max_total_quantity_check
    check (max_total_quantity >= 1),

  constraint menu_option_groups_required_minimum_check
    check (
      (is_required and min_select >= 1)
      or
      (not is_required and min_select = 0)
    ),

  constraint menu_option_groups_selection_rules_check
    check (
      (
        selection_type = 'single'
        and min_select in (0, 1)
        and max_select = 1
        and max_total_quantity = 1
      )
      or
      (
        selection_type = 'multiple'
        and max_total_quantity >= max_select
      )
    ),

  constraint menu_option_groups_menu_id_fkey
    foreign key (menu_id)
    references public.menus (id)
    on update cascade
    on delete cascade,

  constraint menu_option_groups_id_menu_id_key
    unique (id, menu_id)
);

create unique index menu_option_groups_normalized_name_unique
on public.menu_option_groups (
  menu_id,
  lower(btrim(name))
);

create index menu_option_groups_menu_display_order_idx
on public.menu_option_groups (
  menu_id,
  display_order,
  id
);

alter table public.menu_options
add column group_id bigint null;

alter table public.menu_options
add column max_quantity integer not null default 3;

alter table public.menu_options
add constraint menu_options_max_quantity_check
check (max_quantity between 1 and 3);

insert into public.menu_option_groups (
  menu_id,
  name,
  selection_type,
  is_required,
  min_select,
  max_select,
  max_total_quantity,
  display_order,
  is_active
)
select distinct
  menu_options.menu_id,
  'ตัวเลือกเพิ่มเติม',
  'multiple',
  false,
  0,
  3,
  3,
  0,
  true
from public.menu_options
order by menu_options.menu_id;

update public.menu_options
set group_id = menu_option_groups.id
from public.menu_option_groups
where menu_option_groups.menu_id = menu_options.menu_id
  and lower(btrim(menu_option_groups.name)) =
      lower(btrim('ตัวเลือกเพิ่มเติม'))
  and menu_options.group_id is null;

do $$
begin
  if exists (
    select 1
    from public.menu_options
    where group_id is null
  ) then
    raise exception
      'ไม่สามารถย้าย menu_options เดิมเข้ากลุ่ม legacy ได้ครบ';
  end if;
end;
$$;

alter table public.menu_options
add constraint menu_options_group_menu_fkey
foreign key (group_id, menu_id)
references public.menu_option_groups (id, menu_id)
on update cascade
on delete no action;

create index menu_options_group_id_idx
on public.menu_options (group_id);

create unique index menu_options_group_normalized_name_unique
on public.menu_options (
  group_id,
  lower(btrim(name))
)
where group_id is not null;

alter table public.menu_option_groups enable row level security;

revoke all privileges
on table public.menu_option_groups
from anon, authenticated;

grant select, insert, update
on table public.menu_option_groups
to authenticated;

revoke all privileges
on sequence public.menu_option_groups_id_seq
from anon, authenticated;

grant usage, select
on sequence public.menu_option_groups_id_seq
to authenticated;

create policy "authenticated_can_read_menu_option_groups"
on public.menu_option_groups
for select
to authenticated
using (auth.uid() is not null);

create policy "authenticated_can_insert_menu_option_groups"
on public.menu_option_groups
for insert
to authenticated
with check (auth.uid() is not null);

create policy "authenticated_can_update_menu_option_groups"
on public.menu_option_groups
for update
to authenticated
using (auth.uid() is not null)
with check (auth.uid() is not null);

commit;
