begin;
set local lock_timeout = '5s';
set local statement_timeout = '60s';

-- Keep order_item_options.menu_option_id and all existing snapshots intact.
create table public.addons (
  id bigint generated by default as identity primary key,
  name text not null check (btrim(name) <> ''),
  additional_price numeric(12,2) not null check (additional_price >= 0),
  is_available boolean not null default false,
  max_quantity integer not null default 3 check (max_quantity between 1 and 3),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create unique index addons_name_unique on public.addons (lower(btrim(name)));
create table public.addon_ingredients (
  addon_id bigint not null references public.addons(id) on delete restrict,
  ingredient_id bigint not null references public.ingredients(id) on delete restrict,
  quantity_required numeric not null check (quantity_required > 0),
  primary key (addon_id, ingredient_id)
);
alter table public.menu_option_groups add column kind text not null default 'standard'
  check (kind in ('standard','meat','addon'));
alter table public.menu_option_groups add constraint meat_single_selection
  check (kind <> 'meat' or (selection_type = 'single' and max_select = 1 and max_total_quantity = 1));
create unique index one_addon_group_per_menu on public.menu_option_groups(menu_id) where kind = 'addon';
alter table public.menu_options add column addon_id bigint references public.addons(id) on delete restrict;
create unique index menu_addon_unique on public.menu_options(menu_id, addon_id) where addon_id is not null;
alter table public.orders add column dining_type text not null default 'dine_in'
  check (dining_type in ('dine_in','takeaway'));

alter table public.addons enable row level security;
alter table public.addon_ingredients enable row level security;
revoke all on public.addons, public.addon_ingredients from public, anon, authenticated;
grant select, insert, update on public.addons to authenticated;
grant select, insert, update, delete on public.addon_ingredients to authenticated;
grant usage, select on sequence public.addons_id_seq to authenticated;
grant all on public.addons, public.addon_ingredients to service_role;
grant usage, select on sequence public.addons_id_seq to service_role;
create policy staff_addons on public.addons for all to authenticated
  using (auth.uid() is not null) with check (auth.uid() is not null);
create policy staff_addon_recipes on public.addon_ingredients for all to authenticated
  using (auth.uid() is not null) with check (auth.uid() is not null);

-- These views resolve central values at read time. No duplicated addon recipes.
create view public.effective_menu_options with (security_invoker = true) as
select o.id, o.menu_id, o.group_id, o.addon_id,
  case when o.addon_id is null then o.name else a.name end as name,
  case when o.addon_id is null then o.additional_price else a.additional_price end as additional_price,
  o.is_available and coalesce(a.is_available, true) as is_available,
  case when o.addon_id is null then o.max_quantity else a.max_quantity end as max_quantity,
  o.sort_order
from public.menu_options o left join public.addons a on a.id = o.addon_id;
create view public.effective_menu_option_ingredients with (security_invoker = true) as
select r.menu_option_id, r.ingredient_id, r.quantity_required
from public.menu_option_ingredients r join public.menu_options o on o.id = r.menu_option_id
where o.addon_id is null
union all
select o.id, r.ingredient_id, r.quantity_required
from public.menu_options o join public.addon_ingredients r on r.addon_id = o.addon_id;
revoke all on public.effective_menu_options, public.effective_menu_option_ingredients from public, anon;
grant select on public.effective_menu_options, public.effective_menu_option_ingredients to authenticated, service_role;

create function public.save_addon(p_id bigint, p_name text, p_price numeric,
  p_available boolean, p_max_quantity integer, p_recipe jsonb)
returns bigint language plpgsql security invoker set search_path = '' as $$
declare v_id bigint;
begin
  if auth.uid() is null then raise exception 'AUTH_REQUIRED'; end if;
  if nullif(btrim(p_name),'') is null or p_price is null or p_price < 0
    or p_max_quantity is null or p_max_quantity not between 1 and 3 or p_available is null
    or p_recipe is null or jsonb_typeof(p_recipe) <> 'array' then raise exception 'INVALID_ADDON'; end if;
  if p_available and jsonb_array_length(p_recipe) = 0 then raise exception 'RECIPE_REQUIRED'; end if;
  if exists(select 1 from jsonb_to_recordset(p_recipe) r(ingredient_id bigint, quantity_required numeric)
    where r.ingredient_id is null or r.quantity_required is null or r.quantity_required <= 0)
    then raise exception 'INVALID_RECIPE'; end if;
  if p_id is null then
    insert into public.addons(name,additional_price,is_available,max_quantity)
      values(btrim(p_name),p_price,p_available,p_max_quantity) returning id into v_id;
  else
    update public.addons set name=btrim(p_name),additional_price=p_price,is_available=p_available,
      max_quantity=p_max_quantity,updated_at=now() where id=p_id returning id into v_id;
    if not found then raise exception 'ADDON_NOT_FOUND'; end if;
  end if;
  delete from public.addon_ingredients where addon_id=v_id;
  insert into public.addon_ingredients(addon_id,ingredient_id,quantity_required)
    select v_id,r.ingredient_id,r.quantity_required
    from jsonb_to_recordset(p_recipe) r(ingredient_id bigint, quantity_required numeric);
  return v_id;
end $$;

create function public.set_menu_addons(p_menu_id bigint, p_addon_ids bigint[])
returns void language plpgsql security invoker set search_path = '' as $$
declare v_group bigint; v_count integer;
begin
  if auth.uid() is null then raise exception 'AUTH_REQUIRED'; end if;
  if p_addon_ids is null or array_position(p_addon_ids,null) is not null then raise exception 'INVALID_ADDONS'; end if;
  perform id from public.menus where id=p_menu_id for update;
  if not found then raise exception 'MENU_NOT_FOUND'; end if;
  select count(*) into v_count from public.addons where id=any(p_addon_ids);
  if v_count <> cardinality(p_addon_ids) then raise exception 'INVALID_ADDONS'; end if;
  select id into v_group from public.menu_option_groups where menu_id=p_menu_id and kind='addon' for update;
  if v_group is null and v_count=0 then return; end if;
  if v_group is null then
    insert into public.menu_option_groups(menu_id,name,kind,selection_type,is_required,min_select,max_select,max_total_quantity,display_order,is_active)
      values(p_menu_id,'ตัวเลือกเสริม','addon','multiple',false,0,greatest(v_count,1),greatest(v_count*3,3),100,true)
      returning id into v_group;
  else
    update public.menu_option_groups set max_select=greatest(v_count,1),max_total_quantity=greatest(v_count*3,3),is_active=true
      where id=v_group;
  end if;
  -- Unchecking only disables the link; historical option IDs are never deleted.
  update public.menu_options set is_available=false where menu_id=p_menu_id and addon_id is not null;
  insert into public.menu_options(menu_id,group_id,addon_id,name,additional_price,max_quantity,is_available,sort_order)
    select p_menu_id,v_group,a.id,'addon:'||a.id,0,3,true,0 from public.addons a where a.id=any(p_addon_ids)
    on conflict(menu_id,addon_id) where addon_id is not null
      do update set is_available=true,group_id=excluded.group_id;
end $$;
revoke all on function public.save_addon(bigint,text,numeric,boolean,integer,jsonb),
  public.set_menu_addons(bigint,bigint[]) from public, anon;
grant execute on function public.save_addon(bigint,text,numeric,boolean,integer,jsonb),
  public.set_menu_addons(bigint,bigint[]) to authenticated;

create function public.save_menu_with_addons(p_id bigint,p_values jsonb,p_addon_ids bigint[])
returns bigint language plpgsql security invoker set search_path = '' as $$
declare v_id bigint;
begin
  if auth.uid() is null then raise exception 'AUTH_REQUIRED'; end if;
  if nullif(btrim(p_values->>'name'),'') is null or (p_values->>'price')::numeric < 0
    then raise exception 'INVALID_MENU'; end if;
  if p_id is null then
    insert into public.menus(name,description,category_id,price,image_url,is_available)
      values(btrim(p_values->>'name'),nullif(p_values->>'description',''),(p_values->>'category_id')::bigint,
        (p_values->>'price')::numeric,nullif(p_values->>'image_url',''),(p_values->>'is_available')::boolean)
      returning id into v_id;
  else
    update public.menus set name=btrim(p_values->>'name'),description=nullif(p_values->>'description',''),
      category_id=(p_values->>'category_id')::bigint,price=(p_values->>'price')::numeric,
      image_url=nullif(p_values->>'image_url',''),is_available=(p_values->>'is_available')::boolean,updated_at=now()
      where id=p_id returning id into v_id;
    if not found then raise exception 'MENU_NOT_FOUND'; end if;
  end if;
  perform public.set_menu_addons(v_id,p_addon_ids);
  return v_id;
end $$;
revoke all on function public.save_menu_with_addons(bigint,jsonb,bigint[]) from public,anon;
grant execute on function public.save_menu_with_addons(bigint,jsonb,bigint[]) to authenticated;

-- Preserve the proven transaction implementation, invoke through a validating wrapper.
alter function public.create_order_with_stock(bigint,uuid,text,numeric,jsonb,jsonb)
  rename to create_order_with_stock_internal;
revoke all on function public.create_order_with_stock_internal(bigint,uuid,text,numeric,jsonb,jsonb)
  from public, anon, authenticated, service_role;
create function public.create_order_with_stock(p_table_id bigint,p_session_token uuid,p_order_note text,
  p_total_amount numeric,p_items jsonb,p_required_items jsonb,p_dining_type text default 'dine_in')
returns table(id uuid,order_number bigint,table_id bigint,session_id uuid,status text,total_amount numeric,stock_deducted boolean)
language plpgsql security definer set search_path = '' as $$
declare v_item jsonb; v_option jsonb; v_menu public.menus%rowtype;
  v_effective record; v_group record; v_count integer; v_quantity integer;
  v_price numeric; v_required jsonb; v_created record;
begin
  if coalesce(auth.role(),'') <> 'service_role' then raise exception 'SERVICE_ROLE_REQUIRED'; end if;
  if p_dining_type is null or p_dining_type not in ('dine_in','takeaway') then raise exception 'INVALID_DINING_TYPE'; end if;
  if p_items is null or jsonb_typeof(p_items) <> 'array' or jsonb_array_length(p_items)=0 then raise exception 'INVALID_ITEMS'; end if;
  -- Prevent concurrent catalog changes between verification and stock deduction.
  lock table public.menus,public.menu_option_groups,public.menu_options,public.addons,
    public.menu_ingredients,public.menu_option_ingredients,public.addon_ingredients in share mode;
  for v_item in select value from jsonb_array_elements(p_items) loop
    select * into v_menu from public.menus where public.menus.id=(v_item->>'menu_id')::bigint and is_available;
    if not found then raise exception 'MENU_UNAVAILABLE'; end if;
    v_price := v_menu.price;
    if not exists(select 1 from public.menu_ingredients where menu_id=v_menu.id) then raise exception 'RECIPE_REQUIRED'; end if;
    if jsonb_typeof(v_item->'options') <> 'array' then raise exception 'INVALID_OPTIONS'; end if;
    if (select count(*) <> count(distinct value->>'menu_option_id') from jsonb_array_elements(v_item->'options')) then raise exception 'DUPLICATE_OPTIONS'; end if;
    for v_option in select value from jsonb_array_elements(v_item->'options') loop
      select * into v_effective from public.effective_menu_options o
        where o.id=(v_option->>'menu_option_id')::bigint and o.menu_id=v_menu.id and o.is_available;
      if not found then raise exception 'OPTION_UNAVAILABLE'; end if;
      v_quantity := (v_option->>'quantity')::integer;
      if v_quantity is null or v_quantity not between 1 and v_effective.max_quantity
        or (v_option->>'option_name') is distinct from v_effective.name
        or (v_option->>'additional_price')::numeric is distinct from v_effective.additional_price
        then raise exception 'OPTION_CHANGED'; end if;
      if v_effective.group_id is not null and not exists(select 1 from public.menu_option_groups g where g.id=v_effective.group_id and g.is_active)
        then raise exception 'GROUP_UNAVAILABLE'; end if;
      if not exists(select 1 from public.effective_menu_option_ingredients r where r.menu_option_id=v_effective.id)
        then raise exception 'RECIPE_REQUIRED'; end if;
      v_price := v_price + v_effective.additional_price*v_quantity;
    end loop;
    for v_group in select * from public.menu_option_groups where menu_id=v_menu.id and is_active loop
      select count(*),coalesce(sum((s.value->>'quantity')::integer),0) into v_count,v_quantity
        from jsonb_array_elements(v_item->'options') s join public.menu_options o on o.id=(s.value->>'menu_option_id')::bigint
        where o.group_id=v_group.id;
      if v_count < v_group.min_select or v_count > v_group.max_select or v_quantity > v_group.max_total_quantity
        then raise exception 'GROUP_SELECTION_INVALID'; end if;
    end loop;
    if (v_item->>'unit_price')::numeric is distinct from v_price then raise exception 'PRICE_CHANGED'; end if;
  end loop;
  select coalesce(jsonb_agg(jsonb_build_object('ingredient_id',r.ingredient_id,'quantity',r.quantity) order by r.ingredient_id),'[]')
    into v_required from (
      select ingredient_id,sum(quantity) quantity from (
        select r.ingredient_id,r.quantity_required*(i.value->>'quantity')::integer quantity
          from jsonb_array_elements(p_items) i join public.menu_ingredients r on r.menu_id=(i.value->>'menu_id')::bigint
        union all
        select r.ingredient_id,r.quantity_required*(i.value->>'quantity')::integer*(o.value->>'quantity')::integer
          from jsonb_array_elements(p_items) i cross join lateral jsonb_array_elements(i.value->'options') o
          join public.effective_menu_option_ingredients r on r.menu_option_id=(o.value->>'menu_option_id')::bigint
      ) usage group by ingredient_id
    ) r;
  -- Recompute recipes in the database, never trust client/server cached quantities.
  select * into v_created from public.create_order_with_stock_internal(p_table_id,p_session_token,p_order_note,p_total_amount,p_items,v_required);
  update public.orders set dining_type=p_dining_type where public.orders.id=v_created.id;
  return query select v_created.id,v_created.order_number,v_created.table_id,v_created.session_id,
    v_created.status,v_created.total_amount,v_created.stock_deducted;
end $$;
revoke all on function public.create_order_with_stock(bigint,uuid,text,numeric,jsonb,jsonb,text) from public,anon,authenticated;
grant execute on function public.create_order_with_stock(bigint,uuid,text,numeric,jsonb,jsonb,text) to service_role;
create or replace function public.delete_catalog_item_safely(
  p_kind text, p_id bigint, p_name text, p_archive boolean default false
)
returns jsonb
language plpgsql
security invoker
set search_path = ''
set lock_timeout = '5s'
as $$
declare
  v_name text;
  v_recipes jsonb;
begin
  if auth.uid() is null or coalesce(auth.role(), '') <> 'authenticated' then
    raise exception using errcode = '42501', message = 'AUTH_REQUIRED';
  end if;
  if p_kind is null or p_kind not in ('menu', 'ingredient')
     or p_id is null or p_id <= 0 or p_name is null or p_archive is null
     or (p_kind = 'ingredient' and p_archive) then
    raise exception using errcode = '22023', message = 'INVALID_INPUT';
  end if;

  if p_kind = 'menu' then
    select name into v_name from public.menus where id = p_id for update;
  else
    select name into v_name from public.ingredients where id = p_id for update;
  end if;
  if not found then return jsonb_build_object('status', 'not_found'); end if;
  if v_name is distinct from p_name then
    return jsonb_build_object('status', 'name_changed');
  end if;

  if p_kind = 'menu' then
    if p_archive then
      update public.menus set is_available = false, updated_at = now() where id = p_id;
      return jsonb_build_object('status', 'archived');
    end if;

    -- FOR UPDATE conflicts with FK key-share locks: concurrent inserts/edits
    -- cannot create new references between this check and the DELETE.
    perform id from public.menu_options where menu_id = p_id order by id for update;
    if exists (select 1 from public.order_items where menu_id = p_id)
       or exists (
         select 1 from public.order_item_options oi
         join public.menu_options mo on mo.id = oi.menu_option_id
         where mo.menu_id = p_id
       ) then
      return jsonb_build_object('status', 'used');
    end if;
    -- One statement: all owned children cascade or the entire call rolls back.
    delete from public.menus where id = p_id;
  else
    select jsonb_agg(recipe order by recipe) into v_recipes from (
      select distinct 'เมนู “' || m.name || '” (#' || m.id || ') / สูตรพื้นฐาน' as recipe
      from public.menu_ingredients mi join public.menus m on m.id = mi.menu_id
      where mi.ingredient_id = p_id
      union
      select distinct 'เมนู “' || m.name || '” (#' || m.id || ') / ตัวเลือก “' || mo.name || '” (#' || mo.id || ')'
      from public.menu_option_ingredients moi
      join public.menu_options mo on mo.id = moi.menu_option_id
      join public.menus m on m.id = mo.menu_id
      where moi.ingredient_id = p_id
      union
      select distinct 'ตัวเลือกเสริมกลาง “' || a.name || '” (#' || a.id || ')'
      from public.addon_ingredients ar join public.addons a on a.id=ar.addon_id
      where ar.ingredient_id=p_id
    ) refs;
    if v_recipes is not null then
      return jsonb_build_object('status', 'recipe', 'recipes', v_recipes);
    end if;
    if exists (select 1 from public.order_ingredient_usages where ingredient_id = p_id) then
      return jsonb_build_object('status', 'usage');
    end if;
    delete from public.ingredients where id = p_id;
  end if;
  if not found then return jsonb_build_object('status', 'not_found'); end if;
  return jsonb_build_object('status', 'deleted');
end;
$$;


revoke all on function public.delete_catalog_item_safely(text,bigint,text,boolean) from public,anon;
grant execute on function public.delete_catalog_item_safely(text,bigint,text,boolean) to authenticated;
commit;
