-- Disposable baseline from the 2026-09-14 read-only schema audit. No remote data.
create role anon; create role authenticated; create role service_role bypassrls;
create schema auth;
create function auth.uid() returns uuid language sql stable as $$ select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid $$;
create or replace function public.protect_other_ingredient_category()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  if pg_catalog.btrim(old.name) = 'อื่น ๆ' then
    if tg_op = 'DELETE' then
      raise exception 'หมวดวัตถุดิบ "อื่น ๆ" ไม่สามารถลบได้'
        using errcode = '23514';
    end if;

    if new.name is distinct from old.name then
      raise exception 'หมวดวัตถุดิบ "อื่น ๆ" ไม่สามารถเปลี่ยนชื่อได้'
        using errcode = '23514';
    end if;

    if new.is_active is false
      and new.is_active is distinct from old.is_active then
      raise exception 'หมวดวัตถุดิบ "อื่น ๆ" ไม่สามารถปิดใช้งานได้'
        using errcode = '23514';
    end if;
  end if;

  if tg_op = 'DELETE' then
    return old;
  end if;

  return new;
end;
$$;


create function auth.role() returns text language sql stable as $$ select current_setting('request.jwt.claim.role',true) $$;
create table public.categories(id bigint generated by default as identity not null,
name text not null,
description text,
created_at timestamptz default now() not null);
create table public.ingredient_categories(id bigint generated by default as identity not null,
name text not null,
display_order integer default 0 not null,
is_active boolean default true not null,
created_at timestamptz default now() not null);
create table public.ingredients(id bigint generated by default as identity not null,
name text not null,
unit text not null,
stock_quantity numeric default 0 not null,
minimum_stock numeric default 0 not null,
updated_at timestamptz default now() not null,
category_id bigint);
create table public.menus(id bigint generated by default as identity not null,
category_id bigint,
name text not null,
description text,
price numeric not null,
image_url text,
is_available boolean default true not null,
created_at timestamptz default now() not null,
updated_at timestamptz default now() not null);
create table public.menu_option_groups(id bigint generated by default as identity not null,
menu_id bigint not null,
name text not null,
selection_type text not null,
is_required boolean default false not null,
min_select integer default 0 not null,
max_select integer not null,
max_total_quantity integer not null,
display_order integer default 0 not null,
is_active boolean default true not null,
created_at timestamptz default now() not null);
create table public.menu_options(id bigint generated by default as identity not null,
menu_id bigint not null,
name text not null,
additional_price numeric default 0 not null,
is_available boolean default true not null,
sort_order integer default 0 not null,
created_at timestamptz default now() not null,
group_id bigint,
max_quantity integer default 3 not null);
create table public.menu_ingredients(menu_id bigint not null,
ingredient_id bigint not null,
quantity_required numeric not null);
create table public.menu_option_ingredients(id bigint generated by default as identity not null,
menu_option_id bigint not null,
ingredient_id bigint not null,
quantity_required numeric not null,
created_at timestamptz default now() not null);
create table public.restaurant_tables(id bigint generated by default as identity not null,
table_number text not null,
qr_code text not null,
status text default 'available'::text not null,
created_at timestamptz default now() not null);
create table public.dining_sessions(id uuid default gen_random_uuid() not null,
table_id bigint not null,
access_token uuid not null,
status text default 'active'::text not null,
opened_at timestamptz default now() not null,
closed_at timestamptz);
create table public.orders(id uuid default gen_random_uuid() not null,
order_number bigint generated by default as identity not null,
table_id bigint not null,
status text default 'pending'::text not null,
total_amount numeric default 0 not null,
note text,
created_at timestamptz default now() not null,
updated_at timestamptz default now() not null,
stock_deducted boolean default false not null,
session_id uuid);
create table public.order_items(id bigint generated by default as identity not null,
order_id uuid not null,
menu_id bigint not null,
quantity integer not null,
unit_price numeric not null,
subtotal numeric not null,
note text);
create table public.order_item_options(id bigint generated by default as identity not null,
order_item_id bigint not null,
menu_option_id bigint,
option_name text not null,
additional_price numeric default 0 not null,
created_at timestamptz default now() not null,
quantity integer default 1 not null);
create table public.order_ingredient_usages(id bigint generated by default as identity not null,
order_id uuid not null,
ingredient_id bigint not null,
quantity_used numeric not null,
created_at timestamptz default now() not null);
create table public.payments(id uuid default gen_random_uuid() not null,
order_id uuid not null,
payment_method text not null,
amount numeric not null,
status text default 'pending'::text not null,
paid_at timestamptz,
created_at timestamptz default now() not null);
alter table public.restaurant_tables add constraint restaurant_tables_status_check CHECK ((status = ANY (ARRAY['available'::text, 'occupied'::text, 'inactive'::text])));
alter table public.restaurant_tables add constraint restaurant_tables_pkey PRIMARY KEY (id);
alter table public.restaurant_tables add constraint restaurant_tables_table_number_key UNIQUE (table_number);
alter table public.restaurant_tables add constraint restaurant_tables_qr_code_key UNIQUE (qr_code);
alter table public.categories add constraint categories_pkey PRIMARY KEY (id);
alter table public.categories add constraint categories_name_key UNIQUE (name);
alter table public.menus add constraint menus_price_check CHECK ((price >= (0)::numeric));
alter table public.menus add constraint menus_pkey PRIMARY KEY (id);
alter table public.ingredients add constraint ingredients_stock_quantity_check CHECK ((stock_quantity >= (0)::numeric));
alter table public.ingredients add constraint ingredients_minimum_stock_check CHECK ((minimum_stock >= (0)::numeric));
alter table public.ingredients add constraint ingredients_pkey PRIMARY KEY (id);
alter table public.ingredients add constraint ingredients_name_key UNIQUE (name);
alter table public.menu_ingredients add constraint menu_ingredients_quantity_required_check CHECK ((quantity_required > (0)::numeric));
alter table public.menu_ingredients add constraint menu_ingredients_pkey PRIMARY KEY (menu_id, ingredient_id);
alter table public.orders add constraint orders_status_check CHECK ((status = ANY (ARRAY['pending'::text, 'confirmed'::text, 'preparing'::text, 'ready'::text, 'served'::text, 'completed'::text, 'cancelled'::text])));
alter table public.orders add constraint orders_total_amount_check CHECK ((total_amount >= (0)::numeric));
alter table public.orders add constraint orders_pkey PRIMARY KEY (id);
alter table public.orders add constraint orders_order_number_key UNIQUE (order_number);
alter table public.order_items add constraint order_items_quantity_check CHECK ((quantity > 0));
alter table public.order_items add constraint order_items_unit_price_check CHECK ((unit_price >= (0)::numeric));
alter table public.order_items add constraint order_items_subtotal_check CHECK ((subtotal >= (0)::numeric));
alter table public.order_items add constraint order_items_pkey PRIMARY KEY (id);
alter table public.payments add constraint payments_amount_check CHECK ((amount >= (0)::numeric));
alter table public.payments add constraint payments_status_check CHECK ((status = ANY (ARRAY['pending'::text, 'paid'::text, 'failed'::text, 'refunded'::text])));
alter table public.payments add constraint payments_pkey PRIMARY KEY (id);
alter table public.payments add constraint payments_order_id_key UNIQUE (order_id);
alter table public.payments add constraint payments_payment_method_check CHECK ((payment_method = ANY (ARRAY['cash'::text, 'qr_code'::text])));
alter table public.menu_options add constraint menu_options_price_check CHECK ((additional_price >= (0)::numeric));
alter table public.menu_options add constraint menu_options_pkey PRIMARY KEY (id);
alter table public.order_item_options add constraint order_item_options_price_check CHECK ((additional_price >= (0)::numeric));
alter table public.order_item_options add constraint order_item_options_pkey PRIMARY KEY (id);
alter table public.menu_option_ingredients add constraint menu_option_ingredients_quantity_required_check CHECK ((quantity_required > (0)::numeric));
alter table public.menu_option_ingredients add constraint menu_option_ingredients_pkey PRIMARY KEY (id);
alter table public.menu_option_ingredients add constraint menu_option_ingredients_unique UNIQUE (menu_option_id, ingredient_id);
alter table public.order_ingredient_usages add constraint order_ingredient_usages_quantity_used_check CHECK ((quantity_used > (0)::numeric));
alter table public.order_ingredient_usages add constraint order_ingredient_usages_pkey PRIMARY KEY (id);
alter table public.order_ingredient_usages add constraint order_ingredient_usages_order_ingredient_unique UNIQUE (order_id, ingredient_id);
alter table public.dining_sessions add constraint dining_sessions_status_check CHECK ((status = ANY (ARRAY['active'::text, 'closed'::text])));
alter table public.dining_sessions add constraint dining_sessions_pkey PRIMARY KEY (id);
alter table public.dining_sessions add constraint dining_sessions_access_token_key UNIQUE (access_token);
alter table public.order_item_options add constraint order_item_options_quantity_check CHECK (((quantity >= 1) AND (quantity <= 3)));
alter table public.ingredient_categories add constraint ingredient_categories_name_check CHECK ((btrim(name) <> ''::text));
alter table public.ingredient_categories add constraint ingredient_categories_display_order_check CHECK ((display_order >= 0));
alter table public.ingredient_categories add constraint ingredient_categories_pkey PRIMARY KEY (id);
alter table public.menu_option_groups add constraint menu_option_groups_name_not_blank_check CHECK ((btrim(name) <> ''::text));
alter table public.menu_option_groups add constraint menu_option_groups_selection_type_check CHECK ((selection_type = ANY (ARRAY['single'::text, 'multiple'::text])));
alter table public.menu_option_groups add constraint menu_option_groups_display_order_check CHECK ((display_order >= 0));
alter table public.menu_option_groups add constraint menu_option_groups_min_select_check CHECK ((min_select >= 0));
alter table public.menu_option_groups add constraint menu_option_groups_max_select_check CHECK ((max_select >= 1));
alter table public.menu_option_groups add constraint menu_option_groups_select_range_check CHECK ((min_select <= max_select));
alter table public.menu_option_groups add constraint menu_option_groups_max_total_quantity_check CHECK ((max_total_quantity >= 1));
alter table public.menu_option_groups add constraint menu_option_groups_required_minimum_check CHECK (((is_required AND (min_select >= 1)) OR ((NOT is_required) AND (min_select = 0))));
alter table public.menu_option_groups add constraint menu_option_groups_selection_rules_check CHECK ((((selection_type = 'single'::text) AND (min_select = ANY (ARRAY[0, 1])) AND (max_select = 1) AND (max_total_quantity = 1)) OR ((selection_type = 'multiple'::text) AND (max_total_quantity >= max_select))));
alter table public.menu_option_groups add constraint menu_option_groups_pkey PRIMARY KEY (id);
alter table public.menu_option_groups add constraint menu_option_groups_id_menu_id_key UNIQUE (id, menu_id);
alter table public.menu_options add constraint menu_options_max_quantity_check CHECK (((max_quantity >= 1) AND (max_quantity <= 3)));
alter table public.menus add constraint menus_category_id_fkey FOREIGN KEY (category_id) REFERENCES categories(id) ON DELETE SET NULL;
alter table public.menu_ingredients add constraint menu_ingredients_ingredient_id_fkey FOREIGN KEY (ingredient_id) REFERENCES ingredients(id) ON DELETE RESTRICT;
alter table public.menu_ingredients add constraint menu_ingredients_menu_id_fkey FOREIGN KEY (menu_id) REFERENCES menus(id) ON DELETE CASCADE;
alter table public.orders add constraint orders_table_id_fkey FOREIGN KEY (table_id) REFERENCES restaurant_tables(id);
alter table public.order_item_options add constraint order_item_options_menu_option_id_fkey FOREIGN KEY (menu_option_id) REFERENCES menu_options(id) ON DELETE RESTRICT;
alter table public.order_items add constraint order_items_order_id_fkey FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE;
alter table public.order_items add constraint order_items_menu_id_fkey FOREIGN KEY (menu_id) REFERENCES menus(id);
alter table public.payments add constraint payments_order_id_fkey FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE;
alter table public.menu_options add constraint menu_options_menu_id_fkey FOREIGN KEY (menu_id) REFERENCES menus(id) ON DELETE CASCADE;
alter table public.order_item_options add constraint order_item_options_order_item_id_fkey FOREIGN KEY (order_item_id) REFERENCES order_items(id) ON DELETE CASCADE;
alter table public.menu_option_ingredients add constraint menu_option_ingredients_menu_option_id_fkey FOREIGN KEY (menu_option_id) REFERENCES menu_options(id) ON DELETE CASCADE;
alter table public.menu_option_ingredients add constraint menu_option_ingredients_ingredient_id_fkey FOREIGN KEY (ingredient_id) REFERENCES ingredients(id) ON DELETE RESTRICT;
alter table public.order_ingredient_usages add constraint order_ingredient_usages_order_id_fkey FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE;
alter table public.order_ingredient_usages add constraint order_ingredient_usages_ingredient_id_fkey FOREIGN KEY (ingredient_id) REFERENCES ingredients(id);
alter table public.dining_sessions add constraint dining_sessions_table_id_fkey FOREIGN KEY (table_id) REFERENCES restaurant_tables(id);
alter table public.orders add constraint orders_session_id_fkey FOREIGN KEY (session_id) REFERENCES dining_sessions(id);
alter table public.ingredients add constraint ingredients_category_id_fkey FOREIGN KEY (category_id) REFERENCES ingredient_categories(id) ON UPDATE CASCADE ON DELETE SET NULL;
alter table public.menu_option_groups add constraint menu_option_groups_menu_id_fkey FOREIGN KEY (menu_id) REFERENCES menus(id) ON UPDATE CASCADE ON DELETE CASCADE;
alter table public.menu_options add constraint menu_options_group_menu_fkey FOREIGN KEY (group_id, menu_id) REFERENCES menu_option_groups(id, menu_id) ON UPDATE CASCADE;
create unique index menu_option_groups_normalized_name_unique on menu_option_groups(menu_id,lower(btrim(name)));
create unique index menu_options_group_normalized_name_unique on menu_options(group_id,lower(btrim(name))) where group_id is not null;
CREATE OR REPLACE FUNCTION public.complete_order_payment(p_order_id uuid, p_payment_method text)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare
  v_order public.orders%rowtype;
  v_payment_id public.payments.id%type;
begin
  -- ตรวจสอบช่องทางชำระเงิน
  if p_payment_method not in ('cash', 'qr_code') then
    raise exception 'ช่องทางชำระเงินไม่ถูกต้อง';
  end if;

  -- ค้นหาและล็อกออเดอร์
  select *
  into v_order
  from public.orders
  where id = p_order_id
  for update;

  if not found then
    raise exception 'ไม่พบออเดอร์นี้';
  end if;

  -- ต้องพร้อมเสิร์ฟก่อนรับชำระ
  if v_order.status <> 'ready' then
    raise exception 'ออเดอร์ต้องอยู่ในสถานะพร้อมเสิร์ฟก่อนรับชำระ';
  end if;

  -- สต็อกต้องถูกหักตอนเริ่มทำอาหารแล้ว
  if not coalesce(v_order.stock_deducted, false) then
    raise exception 'ออเดอร์นี้ยังไม่ได้หักสต็อก';
  end if;

  -- ป้องกันการชำระซ้ำ โดยตรวจทุกสถานะที่ไม่ใช่ล้มเหลว
  if exists (
    select 1
    from public.payments
    where order_id = p_order_id
      and status not in ('failed', 'cancelled')
  ) then
    raise exception 'ออเดอร์นี้ชำระเงินแล้ว';
  end if;

  -- บันทึกการชำระเงิน
  insert into public.payments (
    order_id,
    payment_method,
    amount,
    status,
    paid_at
  )
  values (
    p_order_id,
    p_payment_method,
    v_order.total_amount,
    'paid',
    now()
  )
  returning id into v_payment_id;

  -- ปิดออเดอร์ โดยไม่หักสต็อกซ้ำ
  update public.orders
  set
    status = 'completed',
    updated_at = now()
  where id = p_order_id;

  return jsonb_build_object(
    'success', true,
    'message', 'รับชำระเงินสำเร็จ',
    'order_id', p_order_id,
    'payment_id', v_payment_id,
    'payment_method', p_payment_method,
    'amount', v_order.total_amount
  );
end;
$function$
;
CREATE OR REPLACE FUNCTION public.deduct_ingredient_stock(required_items jsonb)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare
  item jsonb;
  ingredient_record record;
  required_quantity numeric;
begin
  -- ตรวจทุกวัตถุดิบและล็อกแถวไว้ก่อน
  for item in
    select value
    from jsonb_array_elements(required_items)
  loop
    required_quantity :=
      (item->>'quantity')::numeric;

    select id, name, stock_quantity
    into ingredient_record
    from public.ingredients
    where id = (item->>'ingredient_id')::bigint
    for update;

    if not found then
      raise exception
        'ไม่พบวัตถุดิบรหัส %',
        item->>'ingredient_id';
    end if;

    if ingredient_record.stock_quantity < required_quantity then
      raise exception
        'วัตถุดิบ % ไม่เพียงพอ',
        ingredient_record.name;
    end if;
  end loop;

  -- เมื่อทุกอย่างพอแล้ว จึงหักสต็อก
  for item in
    select value
    from jsonb_array_elements(required_items)
  loop
    update public.ingredients
    set stock_quantity =
      stock_quantity - (item->>'quantity')::numeric
    where id = (item->>'ingredient_id')::bigint;
  end loop;
end;
$function$
;
CREATE OR REPLACE FUNCTION public.process_order_stock(p_order_id uuid, required_items jsonb)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare
  current_order record;
  item jsonb;
  current_ingredient_id bigint;
  current_quantity numeric;
  updated_ingredient_id bigint;
begin
  select id, stock_deducted
  into current_order
  from public.orders
  where id = p_order_id
  for update;

  if not found then
    raise exception 'ไม่พบออเดอร์นี้';
  end if;

  if current_order.stock_deducted then
    raise exception 'ออเดอร์นี้ถูกหักสต็อกแล้ว';
  end if;

  if required_items is null
     or jsonb_typeof(required_items) <> 'array'
     or jsonb_array_length(required_items) = 0 then
    raise exception 'ไม่พบรายการวัตถุดิบที่ต้องหัก';
  end if;

  for item in
    select value
    from jsonb_array_elements(required_items)
  loop
    current_ingredient_id := (item ->> 'ingredient_id')::bigint;
    current_quantity := (item ->> 'quantity')::numeric;

    if current_ingredient_id is null
       or current_quantity is null
       or current_quantity <= 0 then
      raise exception 'ข้อมูลวัตถุดิบไม่ถูกต้อง';
    end if;

    update public.ingredients
    set stock_quantity = stock_quantity - current_quantity
    where id = current_ingredient_id
      and stock_quantity >= current_quantity
    returning id into updated_ingredient_id;

    if updated_ingredient_id is null then
      if not exists (
        select 1
        from public.ingredients
        where id = current_ingredient_id
      ) then
        raise exception 'ไม่พบวัตถุดิบรหัส %', current_ingredient_id;
      end if;

      raise exception 'วัตถุดิบรหัส % มีจำนวนไม่เพียงพอ', current_ingredient_id;
    end if;

    insert into public.order_ingredient_usages (
      order_id,
      ingredient_id,
      quantity_used
    )
    values (
      p_order_id,
      current_ingredient_id,
      current_quantity
    );

    updated_ingredient_id := null;
  end loop;

  update public.orders
  set stock_deducted = true,
      updated_at = now()
  where id = p_order_id;
end;
$function$
;
CREATE OR REPLACE FUNCTION public.restore_order_stock()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
begin
  if new.status = 'cancelled'
     and old.status <> 'cancelled'
     and old.stock_deducted = true then
    if old.status = 'completed' then
      raise exception using errcode = 'P0001', message = 'COMPLETED_ORDER';
    end if;

    if not exists (
      select 1
      from public.order_ingredient_usages as usage
      where usage.order_id = old.id
    ) then
      raise exception using errcode = 'P0001', message = 'ORDER_USAGE_NOT_FOUND';
    end if;

    update public.ingredients as ingredient
    set stock_quantity = ingredient.stock_quantity + usage.quantity_used,
        updated_at = now()
    from public.order_ingredient_usages as usage
    where usage.order_id = old.id
      and ingredient.id = usage.ingredient_id;

    new.stock_deducted := false;
  end if;

  return new;
end;
$function$
;
CREATE OR REPLACE FUNCTION public.deduct_order_stock()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare
  required_item record;
  current_stock numeric;
  ingredient_name text;
begin
  -- ทำงานเฉพาะตอนเปลี่ยนจากสถานะอื่นมาเป็น confirmed
  -- และออเดอร์นี้ยังไม่เคยหักสต็อก
  if new.status = 'confirmed'
     and old.status is distinct from 'confirmed'
     and coalesce(new.stock_deducted, false) = false then

    for required_item in
      select
        mi.ingredient_id,
        sum(mi.quantity_required * oi.quantity) as total_required
      from public.order_items oi
      join public.menu_ingredients mi
        on mi.menu_id = oi.menu_id
      where oi.order_id = new.id
      group by mi.ingredient_id
      order by mi.ingredient_id
    loop
      -- ล็อกวัตถุดิบทีละรายการ เพื่อป้องกันหลายออเดอร์หักพร้อมกัน
      select
        i.name,
        i.stock_quantity
      into
        ingredient_name,
        current_stock
      from public.ingredients i
      where i.id = required_item.ingredient_id
      for update;

      if not found then
        raise exception
          'ไม่พบข้อมูลวัตถุดิบรหัส %',
          required_item.ingredient_id;
      end if;

      if current_stock < required_item.total_required then
        raise exception
          'วัตถุดิบ "%" ไม่เพียงพอ ต้องใช้ % แต่เหลือ %',
          ingredient_name,
          required_item.total_required,
          current_stock;
      end if;

      update public.ingredients
      set
        stock_quantity = stock_quantity - required_item.total_required,
        updated_at = now()
      where id = required_item.ingredient_id;
    end loop;

    new.stock_deducted := true;
  end if;

  return new;
end;
$function$
;
create view public.menu_stock_availability as  SELECT m.id AS menu_id,
    m.is_available AS manually_available,
        CASE
            WHEN (count(mi.ingredient_id) = 0) THEN false
            WHEN bool_and((COALESCE(i.stock_quantity, (0)::numeric) >= mi.quantity_required)) THEN true
            ELSE false
        END AS stock_available,
        CASE
            WHEN ((m.is_available = true) AND (count(mi.ingredient_id) > 0) AND bool_and((COALESCE(i.stock_quantity, (0)::numeric) >= mi.quantity_required))) THEN true
            ELSE false
        END AS can_order
   FROM ((menus m
     LEFT JOIN menu_ingredients mi ON ((mi.menu_id = m.id)))
     LEFT JOIN ingredients i ON ((i.id = mi.ingredient_id)))
  GROUP BY m.id, m.is_available;
CREATE TRIGGER trigger_deduct_order_stock BEFORE UPDATE OF status ON public.orders FOR EACH ROW EXECUTE FUNCTION deduct_order_stock();
CREATE TRIGGER trigger_restore_order_stock BEFORE UPDATE OF status ON public.orders FOR EACH ROW EXECUTE FUNCTION restore_order_stock();
CREATE TRIGGER protect_other_ingredient_category BEFORE DELETE OR UPDATE ON public.ingredient_categories FOR EACH ROW EXECUTE FUNCTION protect_other_ingredient_category();
alter table public.categories enable row level security;
alter table public.ingredient_categories enable row level security;
alter table public.ingredients enable row level security;
alter table public.menus enable row level security;
alter table public.menu_option_groups enable row level security;
alter table public.menu_options enable row level security;
alter table public.menu_ingredients enable row level security;
alter table public.menu_option_ingredients enable row level security;
alter table public.restaurant_tables enable row level security;
alter table public.dining_sessions enable row level security;
alter table public.orders enable row level security;
alter table public.order_items enable row level security;
alter table public.order_item_options enable row level security;
alter table public.order_ingredient_usages enable row level security;
alter table public.payments enable row level security;
create policy "Authenticated users can insert ingredients" on public.ingredients for INSERT to authenticated with check (true);
create policy "Authenticated users can update ingredients" on public.ingredients for UPDATE to authenticated using (true) with check (true);
create policy "Authenticated users can view ingredients" on public.ingredients for SELECT to authenticated using (true);
create policy "Public can view ingredients for availability" on public.ingredients for SELECT to anon,authenticated using (true);
create policy "authenticated_delete_unused_ingredients" on public.ingredients for DELETE to authenticated using ((auth.uid() IS NOT NULL));
create policy "Authenticated users can delete menu ingredients" on public.menu_ingredients for DELETE to authenticated using (true);
create policy "Authenticated users can insert menu ingredients" on public.menu_ingredients for INSERT to authenticated with check (true);
create policy "Authenticated users can read menu ingredients" on public.menu_ingredients for SELECT to authenticated using (true);
create policy "Authenticated users can update menu ingredients" on public.menu_ingredients for UPDATE to authenticated using (true) with check (true);
create policy "Public can view menu ingredients" on public.menu_ingredients for SELECT to anon,authenticated using (true);
create policy "Authenticated users can view order items" on public.order_items for SELECT to authenticated using (true);
create policy "customer_can_create_order_items" on public.order_items for INSERT to anon,authenticated with check (((quantity > 0) AND (unit_price >= (0)::numeric) AND (subtotal >= (0)::numeric)));
create policy "customer_can_read_order_items" on public.order_items for SELECT to anon,authenticated using (true);
create policy "Public can view available menu options" on public.menu_options for SELECT to anon,authenticated using ((is_available = true));
create policy "authenticated_insert_menu_options" on public.menu_options for INSERT to authenticated with check ((auth.uid() IS NOT NULL));
create policy "authenticated_read_all_menu_options" on public.menu_options for SELECT to authenticated using ((auth.uid() IS NOT NULL));
create policy "authenticated_update_menu_options" on public.menu_options for UPDATE to authenticated using ((auth.uid() IS NOT NULL)) with check ((auth.uid() IS NOT NULL));
create policy "authenticated_delete_option_recipes" on public.menu_option_ingredients for DELETE to authenticated using ((auth.uid() IS NOT NULL));
create policy "authenticated_insert_option_recipes" on public.menu_option_ingredients for INSERT to authenticated with check ((auth.uid() IS NOT NULL));
create policy "authenticated_read_option_recipes" on public.menu_option_ingredients for SELECT to authenticated using ((auth.uid() IS NOT NULL));
create policy "authenticated_update_option_recipes" on public.menu_option_ingredients for UPDATE to authenticated using ((auth.uid() IS NOT NULL)) with check ((auth.uid() IS NOT NULL));
create policy "Public can create order item options" on public.order_item_options for INSERT to anon,authenticated with check (true);
create policy "authenticated_read_order_item_options" on public.order_item_options for SELECT to authenticated using ((auth.uid() IS NOT NULL));
create policy "Authenticated users can insert menus" on public.menus for INSERT to authenticated with check (true);
create policy "Authenticated users can update menus" on public.menus for UPDATE to authenticated using (true) with check (true);
create policy "Authenticated users can view menus" on public.menus for SELECT to authenticated using (true);
create policy "Public can view available menus" on public.menus for SELECT to anon,authenticated using ((is_available = true));
create policy "authenticated_delete_unused_menus" on public.menus for DELETE to authenticated using ((auth.uid() IS NOT NULL));
create policy "Authenticated users can read categories" on public.categories for SELECT to authenticated using (true);
create policy "Authenticated users can view restaurant tables" on public.restaurant_tables for SELECT to authenticated using (true);
create policy "Public can view restaurant tables" on public.restaurant_tables for SELECT to anon,authenticated using (true);
create policy "Authenticated users can delete payments" on public.payments for DELETE to authenticated using (true);
create policy "Authenticated users can insert payments" on public.payments for INSERT to authenticated with check (true);
create policy "Authenticated users can view payments" on public.payments for SELECT to authenticated using (true);
create policy "Authenticated users can update orders" on public.orders for UPDATE to authenticated using (true) with check (true);
create policy "Authenticated users can view orders" on public.orders for SELECT to authenticated using (true);
create policy "customer_can_create_orders" on public.orders for INSERT to anon,authenticated with check (((status = 'pending'::text) AND (total_amount >= (0)::numeric)));
create policy "authenticated_read_ingredient_usages" on public.order_ingredient_usages for SELECT to authenticated using ((auth.uid() IS NOT NULL));
create policy "authenticated_can_insert_menu_option_groups" on public.menu_option_groups for INSERT to authenticated with check ((auth.uid() IS NOT NULL));
create policy "authenticated_can_read_menu_option_groups" on public.menu_option_groups for SELECT to authenticated using ((auth.uid() IS NOT NULL));
create policy "authenticated_can_update_menu_option_groups" on public.menu_option_groups for UPDATE to authenticated using ((auth.uid() IS NOT NULL)) with check ((auth.uid() IS NOT NULL));
create policy "authenticated_can_insert_ingredient_categories" on public.ingredient_categories for INSERT to authenticated with check ((auth.uid() IS NOT NULL));
create policy "authenticated_can_read_ingredient_categories" on public.ingredient_categories for SELECT to authenticated using ((auth.uid() IS NOT NULL));
create policy "authenticated_can_update_ingredient_categories" on public.ingredient_categories for UPDATE to authenticated using ((auth.uid() IS NOT NULL)) with check ((auth.uid() IS NOT NULL));
grant usage on schema public,auth to anon,authenticated,service_role;
grant all on all tables in schema public to service_role;
grant select,insert,update,delete on all tables in schema public to authenticated;
grant usage,select on all sequences in schema public to authenticated,service_role;
